### ISSUE TITLE
Can't pass flags to script

### ISSUE THREAD

**Issue by rbreckenridge** [tallesl/qckwinsvc#8]
I'm looking to autostart a node.js file that takes a few arguments on the command line. Can I use qckwinsvc to do this? 

If I do this, it churns out an .exe and creates a service.
`> qckwinsvc --name "name" --description "desc" --script "c:\path\to\node.js" --startImmediately` 

If I do this, I get the error below. 
`> qckwinsvc --name "name" --description "desc" --script "c:\path\to\node.js --web c:\path\to\web localhost:port1 localhost:port2" --startImmediately`

```
fs.js:923
  return binding.mkdir(pathModule._makeLong(path), 

Error: ENOENT: no such file or directory, mkdir 'c:\path\to\node.js --web c:\daemon'
  at Error (native)
  at Object.fs.mkdirSync (fs.js:923:18)
  at c:\...\node-windows\lib\daemon.js:514:16
  at FSReqWrap.cb [as oncomplete] (fs.js.258.19)
```

**Comment by dveter** [comment]
It works if you pass args along the script path, but fails if one of the arguments is "path-like" (like in your example "c:\path\to\web").
